version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:7.4.26-node
    steps:
      - checkout
      - restore_cache:
          key: composer-v2-{{ checksum "backend/composer.lock" }}
      - run: composer install -n --prefer-dist --working-dir=./backend
      - save_cache:
          key: composer-v2-{{ checksum "backend/composer.lock" }}
          paths: backend/vendor
      - restore_cache:
          key: npm-v1-{{ checksum "backend/package-lock.json" }}
      - run:
          working_directory: backend
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_cache:
          key: npm-v1-{{ checksum "backend/package-lock.json" }}
          paths:
            - ./backend/node_modules
      - run:
          command: npm run dev
          working_directory: backend
      - run:
          name: php test test
          command: ./backend/vendor/bin/phpunit --configuration=./backend/phpunit.xml
