version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - run: pwd
      - run: ls
      - run: composer install -n --prefer-dist --working-dir=./backend
      - run: npm ci
      - run: npm run dev
      - run:
          name: php test test
          command: vendor/bin/phpunit
