version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:7.4.26-node
    steps:
      - checkout
      - run: composer update --working-dir=./backend
      - run: composer install -n --prefer-dist --working-dir=./backend
      - run: npm ci  --cwd ./backend
      - run: npm run dev  --cwd ./backend
      - run:
          name: php test test
          command: ./backend/vendor/bin/phpunit --configuration=./backend/phpunit.xml
