version: 2.1
jobs:
  build:
    docker:
      - image: cimg/php:7.4.26-node
      - image: circleci/mysql:8.0
        environment:
          MYSQL_DATABASE: laravel_local
          MYSQL_USER: phper
          MYSQL_ROOT_PASSWORD: secret
    environment:
      APP_ENV: testing
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel_local
      DB_USERNAME: phper
      DB_PASSWORD: secret
    steps:
      - checkout
      - restore_cache:
          key: composer-v2-{{ checksum "backend/composer.lock" }}
      - run: composer install -n --prefer-dist --working-dir=./backend
      - save_cache:
          key: composer-v2-{{ checksum "backend/composer.lock" }}
          paths: backend/vendor
      - restore_cache:
          key: npm-v1-{{ checksum "backend/package-lock.json" }}
      - run:
          working_directory: backend
          name: npm ci
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_cache:
          key: npm-v1-{{ checksum "backend/package-lock.json" }}
          paths:
            - ./backend/node_modules
      - run:
          command: npm run dev
          working_directory: backend
      - run:
          name: get ready for mysql
          command: |
            sudo apt-get update
            sudo apt-get install libpq-dev
            sudo docker-php-ext-install pdo_mysql
            dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: php test test
          command: ./backend/vendor/bin/phpunit --configuration=./backend/phpunit.xml
